Repository 5-logic/the-sync-frontend, pull requests merged in 2025-07, with the labels that each got.

#148 Feature/task 140 - Assign lecturer review
  src/app/(dashboard)/lecturer/assign-lecturer-review/page.tsx
  src/components/features/lecturer/AssignLecturerReview/AssignReviewerModal.tsx
  src/components/features/lecturer/AssignLecturerReview/GroupTable.tsx
  src/components/features/lecturer/AssignLecturerReview/SearchFilterBar.tsx
  src/components/features/lecturer/AssignLecturerReview/index.tsx
  src/data/group.ts
  src/data/lecturers.ts
  src/data/review.ts
  src/data/semester.ts
  src/data/submission.ts
Labels: enhancement

#138 Feature/task 134 - Lecturer Group Reivew
  src/app/(dashboard)/lecturer/group-review/page.tsx
  src/components/features/lecturer/GroupReview/ReviewChecklistTable.tsx
  src/components/features/lecturer/GroupReview/ReviewHeader.tsx
  src/components/features/lecturer/GroupReview/index.tsx
  src/data/checklist.ts
Labels: enhancement

#165 Feature/task 150 - checklist
  public/files/Create Checklist Template.xlsx
  public/files/Create List Lecturers Template.xlsx
  public/files/Create List Students Template.xlsx
  src/app/(dashboard)/lecturer/checklist-detail/page.tsx
  src/app/(dashboard)/lecturer/checklist-edit/page.tsx
  src/app/(dashboard)/lecturer/checklist-management/page.tsx
  src/app/(dashboard)/lecturer/create-checklist/page.tsx
  src/components/common/DownloadTemplateButton/DownloadTemplateButton.tsx
  src/components/common/DownloadTemplateButton/index.ts
  src/components/features/admin/CreateNewUser/ExcelImportForm.tsx
  src/components/features/lecturer/AssignLecturerReview/SearchFilterBar.tsx
  src/components/features/lecturer/AssignLecturerReview/SemesterMilestoneSelect.tsx
  src/components/features/lecturer/ChecklistDetail/ChecklistInfoCard.tsx
  src/components/features/lecturer/ChecklistDetail/ChecklistItemTable.tsx
  src/components/features/lecturer/ChecklistDetail/index.tsx
  src/components/features/lecturer/ChecklistEdit/index.tsx
  src/components/features/lecturer/ChecklistManagement/ChecklistTable.tsx
  src/components/features/lecturer/ChecklistManagement/ChecklistToolbar.tsx
  src/components/features/lecturer/ChecklistManagement/index.tsx
  src/components/features/lecturer/CreateChecklist/ChecklistCommonHeader.tsx
  src/components/features/lecturer/CreateChecklist/ChecklistDeleteButton.tsx
  src/components/features/lecturer/CreateChecklist/ChecklistDragger.tsx
  src/components/features/lecturer/CreateChecklist/ChecklistForm.tsx
  src/components/features/lecturer/CreateChecklist/index.tsx
  src/data/ChecklistItems.ts
  src/data/checklist.ts
  src/data/group.ts
  src/data/milestone.ts
Labels: enhancement

#177 Feature/task 175: Student view thesis detail
  src/app/(dashboard)/student/list-thesis/[id]/page.tsx
  src/app/(dashboard)/student/thesis-detail/page.tsx
  src/components/features/student/ViewThesisDetail/ActionButtons.tsx
  src/components/features/student/ViewThesisDetail/ThesisInfoCard.tsx
  src/components/features/student/ViewThesisDetail/index.tsx
Labels: enhancement

#206 Feature/task 204 Student Invite To Group
  src/app/(dashboard)/student/invite-to-group/page.tsx
  src/components/features/student/InviteToGroup/StudentSearch.tsx
  src/components/features/student/InviteToGroup/StudentSuggestionCard.tsx
  src/components/features/student/InviteToGroup/StudentTable.tsx
  src/components/features/student/InviteToGroup/index.tsx
  src/data/student.ts
Labels: enhancement

#212 [FE] Integrate API for View Student's profile
  src/app/(dashboard)/student/page.tsx
  src/app/(dashboard)/student/profile/[id]/page.tsx
  src/components/common/Breadcrumb/index.tsx
  src/components/common/GroupStatusGuard.tsx
  src/components/common/RequestsManagement/RequestsActions.tsx
  src/components/common/RequestsManagement/RequestsDialog.tsx
  src/components/common/RequestsManagement/RequestsTable.tsx
  src/components/features/student/FormOrJoinGroup/CreateGroup/CreateGroupInviteMembersSimple.tsx
  src/components/features/student/FormOrJoinGroup/CreateGroup/InviteTeamMembers.tsx
  src/components/features/student/GroupDashboard/GroupMembersCard.tsx
  src/components/features/student/StudentInfoCard/index.tsx
  src/components/layout/Sidebar/student/StudentSidebar.tsx
  src/contexts/GroupStatusContext.tsx
  src/hooks/index.ts
  src/hooks/student/index.ts
  src/hooks/student/useStudentGroupStatus.ts
  src/hooks/student/useStudentInvite.ts
  src/hooks/student/useStudentInviteHandlers.ts
  src/hooks/student/useStudentProfile.ts
  src/hooks/student/useStudentRequestStatus.ts
  src/lib/services/groups.service.ts
Labels: enhancement

#213 [FE] Integrate API for View Student's profile
  src/app/(dashboard)/student/page.tsx
  src/app/(dashboard)/student/profile/[id]/page.tsx
  src/components/common/Breadcrumb/index.tsx
  src/components/common/GroupStatusGuard.tsx
  src/components/common/RequestsManagement/RequestsActions.tsx
  src/components/common/RequestsManagement/RequestsDialog.tsx
  src/components/common/RequestsManagement/RequestsTable.tsx
  src/components/features/student/FormOrJoinGroup/CreateGroup/CreateGroupInviteMembersSimple.tsx
  src/components/features/student/FormOrJoinGroup/CreateGroup/InviteTeamMembers.tsx
  src/components/features/student/GroupDashboard/GroupMembersCard.tsx
  src/components/features/student/StudentInfoCard/index.tsx
  src/components/layout/Sidebar/student/StudentSidebar.tsx
  src/contexts/GroupStatusContext.tsx
  src/hooks/index.ts
  src/hooks/student/index.ts
  src/hooks/student/useStudentGroupStatus.ts
  src/hooks/student/useStudentInvite.ts
  src/hooks/student/useStudentInviteHandlers.ts
  src/hooks/student/useStudentProfile.ts
  src/hooks/student/useStudentRequestStatus.ts
  src/lib/services/groups.service.ts
Labels: enhancement

#174 Feature/task 172: Student_View_List_Thesis
  src/app/(dashboard)/student/list-thesis/page.tsx
  src/components/features/student/ViewListThesis/ThesisCard.tsx
  src/components/features/student/ViewListThesis/index.tsx
  src/data/thesis.ts
Labels: enhancement

#216 [FE] Integrate API for feature assign student (not group) to other group
  src/app/(auth)/forgot-password/page.tsx
  src/app/(dashboard)/student/list-thesis/page.tsx
  src/app/(dashboard)/student/page.tsx
  src/components/auth/OtpVerificationErrorHandler.tsx
  src/components/auth/OtpVerificationSuccessHandler.tsx
  src/components/auth/PasswordResetEmailForm.tsx
  src/components/auth/PasswordResetErrorHandler.tsx
  src/components/auth/PasswordResetOtpForm.tsx
  src/components/auth/PasswordResetSuccess.tsx
  src/components/auth/PasswordResetSuccessHandler.tsx
  src/components/features/lecturer/AssignStudent/GroupAssignTable.tsx
  src/components/features/lecturer/AssignStudent/GroupTable.tsx
  src/components/features/lecturer/AssignStudent/StudentFilterBar.tsx
  src/components/features/lecturer/AssignStudent/StudentTable.tsx
  src/components/features/lecturer/AssignStudent/index.tsx
  src/components/features/lecturer/AssignStudentDetail/AssignConfirmModal.tsx
  src/components/features/lecturer/AssignStudentDetail/GroupInfoCard.tsx
  src/components/features/lecturer/AssignStudentDetail/TeamMembers.tsx
  src/components/features/lecturer/AssignStudentDetail/index.tsx
  src/components/features/lecturer/AssignSupervisor/GroupOverviewTable.tsx
  src/components/features/student/Home/GroupInformationCard.tsx
  src/components/features/student/Home/ProjectMilestonesCard.tsx
  src/components/features/student/Home/ThesisStatusCard.tsx
  src/components/features/student/Home/index.tsx
  src/components/features/student/ViewListThesis/ThesisCard.tsx
  src/components/features/student/ViewListThesis/index.tsx
  src/data/group.ts
  src/data/studentGroup.ts
  src/data/thesis.ts
  src/lib/services/auth/index.ts
  src/lib/services/auth/password.service.ts
  src/lib/services/groups.service.ts
  src/lib/services/http/interceptors.ts
  src/lib/utils/auth/token-manager.ts
  src/schemas/auth.ts
  src/schemas/forgot-password.ts
  src/store/useGroupsStore.ts
  src/store/useStudentStore.ts
Labels: enhancement

#220 [FE] Integrate API for feature assign student (not group) to other group
  src/components/features/lecturer/AssignStudent/GroupAssignTable.tsx
  src/components/features/lecturer/AssignStudent/GroupTable.tsx
  src/components/features/lecturer/AssignStudent/StudentFilterBar.tsx
  src/components/features/lecturer/AssignStudent/StudentTable.tsx
  src/components/features/lecturer/AssignStudent/index.tsx
  src/components/features/lecturer/AssignStudentDetail/AssignConfirmModal.tsx
  src/components/features/lecturer/AssignStudentDetail/GroupInfoCard.tsx
  src/components/features/lecturer/AssignStudentDetail/TeamMembers.tsx
  src/components/features/lecturer/AssignStudentDetail/index.tsx
  src/components/features/lecturer/AssignSupervisor/GroupOverviewTable.tsx
  src/lib/services/groups.service.ts
  src/store/useGroupsStore.ts
  src/store/useStudentStore.ts
Labels: enhancement

#222 Fix error in create thesis
  src/components/features/lecturer/CreateThesis/ThesisForm.tsx
Labels: bug

#223 [FE] Integrate API for Group Student pick Thesis
  src/components/common/BaseThesisInfoCard.tsx
  src/components/common/Breadcrumb/index.tsx
  src/components/features/lecturer/CreateThesis/ThesisForm.tsx
  src/components/features/lecturer/EditThesis/index.tsx
  src/components/features/lecturer/ViewThesisDetail/ThesisInfoCard.tsx
  src/components/features/student/GroupDashboard/GroupDashboard.tsx
  src/components/features/student/GroupDashboard/GroupDashboardHeader.tsx
  src/components/features/student/GroupDashboard/GroupInfoCard.tsx
  src/components/features/student/GroupDashboard/GroupMembersCard.tsx
  src/components/features/student/GroupDashboard/NoThesisCard.tsx
  src/components/features/student/GroupDashboard/ProgressOverviewCard.tsx
  src/components/features/student/GroupDashboard/SupervisorInfoCard.tsx
  src/components/features/student/GroupDashboard/ThesisStatusCard.tsx
  src/components/features/student/ViewListThesis/ThesisCard.tsx
  src/components/features/student/ViewListThesis/index.tsx
  src/components/features/student/ViewThesisDetail/ActionButtons.tsx
  src/components/features/student/ViewThesisDetail/AssignedGroupCard.tsx
  src/components/features/student/ViewThesisDetail/ThesisInfoCard.tsx
  src/components/features/student/ViewThesisDetail/index.tsx
  src/data/checklist.ts
  src/data/thesis.ts
  src/hooks/student/useSemesterStatus.ts
  src/hooks/student/useStudentGroupStatus.ts
  src/hooks/thesis/index.ts
  src/hooks/thesis/useThesisDetail.ts
  src/hooks/thesis/useThesisRegistration.ts
  src/lib/services/groups.service.ts
  src/lib/services/supervisions.service.ts
  src/lib/services/theses.service.ts
  src/schemas/group.ts
  src/schemas/thesis.ts
  src/store/useGroupDashboardStore.ts
  src/store/useSupervisionsStore.ts
  src/store/useThesisStore.ts
Labels: enhancement

#236 [FE] Integrate API for Group Student pick Thesis
  src/components/common/BaseThesisInfoCard.tsx
  src/components/common/Breadcrumb/index.tsx
  src/components/features/lecturer/EditThesis/index.tsx
  src/components/features/lecturer/ViewThesisDetail/ThesisInfoCard.tsx
  src/components/features/student/GroupDashboard/GroupDashboard.tsx
  src/components/features/student/GroupDashboard/GroupDashboardHeader.tsx
  src/components/features/student/GroupDashboard/GroupInfoCard.tsx
  src/components/features/student/GroupDashboard/GroupMembersCard.tsx
  src/components/features/student/GroupDashboard/NoThesisCard.tsx
  src/components/features/student/GroupDashboard/ProgressOverviewCard.tsx
  src/components/features/student/GroupDashboard/SupervisorInfoCard.tsx
  src/components/features/student/GroupDashboard/ThesisStatusCard.tsx
  src/components/features/student/ViewListThesis/ThesisCard.tsx
  src/components/features/student/ViewListThesis/index.tsx
  src/components/features/student/ViewThesisDetail/ActionButtons.tsx
  src/components/features/student/ViewThesisDetail/AssignedGroupCard.tsx
  src/components/features/student/ViewThesisDetail/ThesisInfoCard.tsx
  src/components/features/student/ViewThesisDetail/index.tsx
  src/data/checklist.ts
  src/data/thesis.ts
  src/hooks/student/useSemesterStatus.ts
  src/hooks/student/useStudentGroupStatus.ts
  src/hooks/thesis/index.ts
  src/hooks/thesis/useThesisDetail.ts
  src/hooks/thesis/useThesisRegistration.ts
  src/lib/services/groups.service.ts
  src/lib/services/supervisions.service.ts
  src/lib/services/theses.service.ts
  src/schemas/group.ts
  src/schemas/thesis.ts
  src/store/useGroupDashboardStore.ts
  src/store/useSupervisionsStore.ts
  src/store/useThesisStore.ts
Labels: enhancement

#239 Feature/task 234: assign lecturer review (client)
  src/app/(dashboard)/student/suggested-thesis/page.tsx
  src/components/features/student/TrackProgress/MilestoneStep.tsx
  src/components/pages/lecturer/LecturerAssignLecturerReviewClient.tsx
Labels: enhancement

#207 Feature/task 204: Student_Invite_to_Group
  src/app/(dashboard)/student/invite-to-group/page.tsx
  src/components/features/student/InviteToGroup/StudentSearch.tsx
  src/components/features/student/InviteToGroup/StudentSuggestionCard.tsx
  src/components/features/student/InviteToGroup/StudentTable.tsx
  src/components/features/student/InviteToGroup/index.tsx
  src/data/student.ts
Labels: enhancement

#225 [FE] System Logic & UI Refinement
  src/app/(dashboard)/lecturer/account-setting/page.tsx
  src/components/features/admin/LecturerManagement/LecturerFilterBar.tsx
  src/components/features/admin/SemesterSettings/SemesterForm.tsx
  src/components/features/admin/SemesterSettings/SemesterTable.tsx
  src/components/features/lecturer/ProfileSetting/index.tsx
  src/components/layout/Header/NotificationIcon.tsx
  src/components/layout/Header/UserProfile.tsx
  src/components/layout/Header/index.tsx
  src/components/pages/lecturer/ProfileSettingsClient.tsx
  src/lib/services/lecturers.service.ts
  src/schemas/semester.ts
Labels: bug, good first issue

#243 [FE] Fix some bugs and update stuffs
  src/components/common/RequestsManagement/RequestsDialog.tsx
  src/components/features/lecturer/AssignListPublishThesis/ThesisTable.tsx
  src/components/features/lecturer/CreateThesis/ThesisForm.tsx
  src/components/features/lecturer/ThesisManagement/ThesisTable.tsx
  src/components/features/lecturer/ViewThesisDetail/ActionButtons.tsx
  src/components/features/lecturer/ViewThesisDetail/index.tsx
  src/components/features/student/GroupDashboard/EditGroupInfoDialog.tsx
  src/components/features/student/GroupDashboard/GroupInfoCard.tsx
  src/lib/auth/providers/credentials.ts
  src/lib/services/groups.service.ts
  src/lib/utils/auth/profile-fetcher.ts
Labels: bug, enhancement

#253 Feature/task 242: Dashboard
  src/app/(dashboard)/admin/page.tsx
  src/app/(dashboard)/lecturer/dashboard-moderator/page.tsx
  src/app/(dashboard)/lecturer/page.tsx
  src/components/common/Dashboard/DashboardStats.tsx
  src/components/common/Dashboard/GroupTableInfo.tsx
  src/components/common/Dashboard/ProgressOverview.tsx
  src/components/common/Dashboard/StatCard.tsx
  src/components/common/Dashboard/SupervisorLoadChart.tsx
  src/components/common/Dashboard/index.tsx
  src/components/features/lecturer/Dashboard/AssignedGroupsTable.tsx
  src/components/features/lecturer/Dashboard/DashboardStats.tsx
  src/components/features/lecturer/Dashboard/MilestonesTimeline.tsx
  src/components/features/lecturer/Dashboard/MyThesisSection.tsx
  src/components/features/lecturer/Dashboard/index.tsx
  src/components/features/student/SuggestedThesis/TopicCard.tsx
  src/data/group.ts
  src/data/milestone.ts
  src/data/moderatorStats.ts
Labels: enhancement

#259 Feature/task 255: Capstone Project Management (Admin)
  src/app/(dashboard)/admin/capstone-defense-results/page.tsx
  src/app/(dashboard)/admin/capstone-project-management/page.tsx
  src/components/features/admin/CapstoneDefenseResults/index.tsx
  src/components/features/admin/CapstoneProjectManagement/Columns.tsx
  src/components/features/admin/CapstoneProjectManagement/FilterBar.tsx
  src/components/features/admin/CapstoneProjectManagement/GroupManagement.tsx
  src/components/features/admin/CapstoneProjectManagement/HighlightText.tsx
  src/components/features/admin/CapstoneProjectManagement/RowSpanCell.tsx
  src/components/features/admin/CapstoneProjectManagement/calculateRowSpan.ts
  src/components/features/admin/CapstoneProjectManagement/index.tsx
  src/components/features/admin/CapstoneProjectManagement/useGroupTableData.ts
  src/components/features/lecturer/Dashboard/AssignedGroupsTable.tsx
  src/components/features/student/Home/GroupInformationCard.tsx
  src/data/group.ts
  src/data/mockStudentMembers.ts
  src/data/thesisData.ts
  src/hooks/ui/useDebounce.ts
  src/styles/components.css
Labels: enhancement

#264 Feature/task 261: Export excel for Capstone Project && Capstone Defense Results
  package.json
  pnpm-lock.yaml
  src/components/features/admin/CapstoneDefenseResults/index.tsx
  src/components/features/admin/CapstoneProjectManagement/FilterBar.tsx
  src/components/features/admin/CapstoneProjectManagement/GroupManagement.tsx
  src/lib/utils/defenseResultsExporter.ts
  src/lib/utils/excelExporter.ts
  src/lib/utils/excelStyles.ts
Labels: enhancement

#269 [FE] Integrate API for AI check duplicate thesis
  package.json
  pnpm-lock.yaml
  src/components/common/BaseThesisInfoCard.tsx
  src/components/features/admin/CapstoneDefenseResults/index.tsx
  src/components/features/admin/CapstoneProjectManagement/FilterBar.tsx
  src/components/features/admin/CapstoneProjectManagement/GroupManagement.tsx
  src/components/features/lecturer/CreateThesis/ThesisForm.tsx
  src/components/features/lecturer/ThesisManagement/ThesisTable.tsx
  src/components/features/lecturer/ViewThesisDetail/ActionButtons.tsx
  src/components/features/lecturer/ViewThesisDetail/DuplicateThesesModal.tsx
  src/components/features/lecturer/ViewThesisDetail/DuplicateThesisCard.tsx
  src/components/features/lecturer/ViewThesisDetail/index.tsx
  src/components/layout/Header/CurrentSemesterTag.tsx
  src/components/layout/Header/index.tsx
  src/hooks/index.ts
  src/hooks/semester/index.ts
  src/hooks/semester/useCurrentSemester.ts
  src/hooks/thesis/index.ts
  src/hooks/thesis/useAiDuplicateCheck.ts
  src/hooks/thesis/useThesisActions.ts
  src/lib/services/ai-duplicate.service.ts
  src/lib/services/theses.service.ts
  src/lib/utils/defenseResultsExporter.ts
  src/lib/utils/excelExporter.ts
  src/lib/utils/excelStyles.ts
Labels: enhancement

#285 hotfix release 0.6.2
  src/components/common/ProgressOverview/ProgressOverviewCard.tsx
  src/components/features/admin/CreateNewUser/ExcelImportForm.tsx
  src/components/features/admin/CreateNewUser/UserForm.tsx
  src/components/features/admin/MilestoneManagement/CreateMilestoneForm.tsx
  src/components/features/admin/MilestoneManagement/EditMilestoneDialog.tsx
  src/components/features/admin/MilestoneManagement/MilestoneForm.tsx
  src/components/features/admin/MilestoneManagement/MilestoneTable.tsx
  src/components/features/lecturer/AssignStudentDetail/ThesisCard.tsx
  src/components/features/lecturer/AssignStudentDetail/ThesisDetailModal.tsx
  src/components/features/lecturer/AssignStudentDetail/index.tsx
  src/components/features/lecturer/GroupManagement/GroupAssignTable.tsx
  src/components/features/student/GroupDashboard/GroupDashboard.tsx
  src/components/features/student/GroupDashboard/StudentEditThesisModal.tsx
  src/components/features/student/GroupDashboard/ThesisStatusCard.tsx
  src/components/features/student/TrackProgress/MilestoneDetail/SubmittedFilesView.tsx
  src/components/features/student/TrackProgress/MilestoneDetailCard.tsx
  src/components/features/student/ViewListThesis/ThesisCard.tsx
  src/components/features/student/ViewListThesis/index.tsx
  src/components/features/student/ViewThesisDetail/ThesisInfoCard.tsx
  src/components/features/student/ViewThesisDetail/index.tsx
  src/components/layout/Header/CurrentSemesterTag.tsx
  src/lib/constants/semester.tsx
  src/schemas/milestone.ts
Labels: bug, enhancement

#287 hotfix release 0.6.3
  src/app/(dashboard)/lecturer/dashboard-moderator/page.tsx
  src/components/features/lecturer/AssignListPublishThesis/ThesisTable.tsx
  src/components/features/lecturer/AssignListPublishThesis/index.tsx
  src/components/features/lecturer/AssignSupervisor/AssignSupervisorModal.tsx
  src/components/features/lecturer/AssignSupervisor/index.tsx
  src/components/layout/Sidebar/lecturer/LecturerSidebar.config.ts
  src/components/layout/Sidebar/lecturer/LecturerSidebar.tsx
  src/components/pages/lecturer/LecturerModeratorDashboardClient.tsx
  src/lib/auth/config/auth-constants.ts
  src/store/usePublishThesesStore.ts
  src/store/useSupervisionStore.ts
Labels: bug, enhancement
